// Code generated by go generate; DO NOT EDIT.
// Generated at 2026-01-30 15:06:18.506352367 -0800 PST m=+1.032178155
// For version 1.9.0, base URL https://broth.itch.zone/libc7zip
package formulas

import "github.com/itchio/boar/szextractor/types"

var ByOsArch = types.DepSpecMap{
	"darwin-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2094840, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "13761e0e8c1232741f164cee36a4d9d9d25bfb49",
					}, types.DepHash{
						Algo: "sha256", Value: "ce3c2af11eead60ffb9d37aff77ab434fc48663b3c2a1d40586259a1bac4ac6d",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.dylib", Size: 148392, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "3dddc24ddc691a7bdbdc965b82631dad78e04454",
					}, types.DepHash{
						Algo: "sha256", Value: "e258106d10224324c3e13be3d56cf027c5d3fafc84d97edf3d51452b9b79730b",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-amd64/1.9.0/.zip",
		},
	}, "darwin-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2092056, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "74c407f13f20818715e717c429ea4b35a61ca601",
					}, types.DepHash{
						Algo: "sha256", Value: "cd03e851931f1e5e356e44ad3e611e9cdb7c7985199a214bc915fffe8e405dcf",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.dylib", Size: 179600, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "279a07299c006f82578d863c19b8992bae7fbe41",
					}, types.DepHash{
						Algo: "sha256", Value: "7715bc55baf65ea14c818f0fb816f5dc997292af6a4fd0a7b4a3be8095259909",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-arm64/1.9.0/.zip",
		},
	}, "linux-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2225664, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "090edb1bdd7b61899561787c5b249383408e191c",
					}, types.DepHash{
						Algo: "sha256", Value: "334ed1aaaacd3ddefb41db6ae7c3d766d40782095e7a1ed6c7105b3ca9d1ba88",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 215232, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "8af2a66d197a69e7d3aa7bf71703985f75e3ec1e",
					}, types.DepHash{
						Algo: "sha256", Value: "0370a19507b3c54e3ee8730feb344f54dc5819775f2c80a27d970084f9178c7c",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-amd64/1.9.0/.zip",
		},
	}, "linux-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2323792, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "a8c15e3621e326a0298dbcb516d7bb469ccbc2b2",
					}, types.DepHash{
						Algo: "sha256", Value: "a323bce742109c23c89a4353e44f47ce36bb7b71c4ac8574e00ddedacd587868",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 208744, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "319ce9950e0b80015023cd9160ad08835b7a8b31",
					}, types.DepHash{
						Algo: "sha256", Value: "3c745898e13fa7084a1c0e51ec11864ba612ba5f4dc883a874c76c814d2c63d9",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-arm64/1.9.0/.zip",
		},
	}, "windows-386": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1332176, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "97728a602ef6e38e5678520d25004a9768011f05",
					}, types.DepHash{
						Algo: "sha256", Value: "1961a0a8f20deb3a9433001b8e9653348c89f69d62c6ec20fefc407f9327f227",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 408528, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "569205f3395088792678ebe541f97dde22925dd1",
					}, types.DepHash{
						Algo: "sha256", Value: "1ceedbcfdf5ac33ea9ba29ec95ac4388a9d1aefc2bca1e49f242947767683468",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-386/1.9.0/.zip",
		},
	}, "windows-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1922000, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "2ebbf31476b7fa91d07fc5a2e7216a31c4e21101",
					}, types.DepHash{
						Algo: "sha256", Value: "4b77ce85d5cac538cc2b1a2d498af607dd5650975fd67549422702545290ef57",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 522712, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "cc5151e88cd8ee0f37cbb42d18078d1eb4d56947",
					}, types.DepHash{
						Algo: "sha256", Value: "9f79ae9b22d4b5a608eb35987419731ca85c7e531c9a9fa0af8099f783b6b9f5",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-amd64/1.9.0/.zip",
		},
	}, "windows-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1784784, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "a1c8390f08e331b4e83dfd60cfea4defc5b88eaa",
					}, types.DepHash{
						Algo: "sha256", Value: "c98c17be5ceecbbe9a88586c9a131c54980f95cf20e4eb22288096ce721940eb",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 529872, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "cc4f446cf5f937a7c6efa964a26f9f037d1cdce1",
					}, types.DepHash{
						Algo: "sha256", Value: "f69d0caaf3f2c9facc3a7fb9512caf4c45b1f6d2e79c97c9ac31a5c8e1c869ae",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-arm64/1.9.0/.zip",
		},
	},
}
