// Code generated by go generate; DO NOT EDIT.
// Generated at 2026-09-14 12:53:58.251234514 -0700 PDT m=+0.743589846
// For version 1.10.0, base URL https://broth.itch.zone/libc7zip
package formulas

import "github.com/itchio/boar/szextractor/types"

var ByOsArch = types.DepSpecMap{
	"darwin-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2513200, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "c57611d79e65b12e967e36a938209fd585c34663",
					}, types.DepHash{
						Algo: "sha256", Value: "6ea6273eafc45fc3dc22114c5890b778faaa6604ce1922256ed95b11dffc5bf2",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.dylib", Size: 148712, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "ab6c15dc81de6130411eeb1bcc863d230a484478",
					}, types.DepHash{
						Algo: "sha256", Value: "a537308222cb3f55ad25637ef9f343850dd1a1ab393de9673a703436e26b5e60",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-amd64/1.10.0/.zip",
		},
	}, "darwin-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2512552, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "7b409fd12a67cb8d73a147362108b3ecb9160866",
					}, types.DepHash{
						Algo: "sha256", Value: "7c8def3afa4c0301be8f5e09dbe7948185ef85aba94c9d073f05ecffdbf77320",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.dylib", Size: 181632, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "49c2ad1bbe5f64f9742147838f2dbb937045bccf",
					}, types.DepHash{
						Algo: "sha256", Value: "7b55dd133d0db5ca0d01cb794c32ad328bcfd1a9cd065f657a7c356cd57e2a30",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-arm64/1.10.0/.zip",
		},
	}, "linux-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2960360, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "e08c681037353c6f69e191b75f0864e7b6491d35",
					}, types.DepHash{
						Algo: "sha256", Value: "065a965d84b5ad753298062e5a5b1f44eab61974060208032a9c806c7ba1b41a",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 224208, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "52e5de8973a3d5457e648d9735c8282f8a1b6c08",
					}, types.DepHash{
						Algo: "sha256", Value: "e440d665638cb5294a2c3edbbbbe191ecbd4cf26f361b57abc6de5026c10d892",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-amd64/1.10.0/.zip",
		},
	}, "linux-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2771808, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "46e0fbde02f3c843edde3781c31f3e79cdf47d56",
					}, types.DepHash{
						Algo: "sha256", Value: "9802528fd74b3510397079c91e7c796ffcf908afcaad9f8aea45cbe74ab511f7",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 213464, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "f7f21e801d7ffccc6ede3abd0f53b9ae2bcd1158",
					}, types.DepHash{
						Algo: "sha256", Value: "76d4a9e837819caeb6f57f2be31ce582fdff931727180710fd80c6a108d3ea63",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-arm64/1.10.0/.zip",
		},
	}, "windows-386": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1333024, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "3a8de58f1fbddf44cbad6993c3716d036a66c5af",
					}, types.DepHash{
						Algo: "sha256", Value: "dedc58e8fce38895e0963df91048fe17b21e18ee83ac5a08753c71d26e6129be",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 509720, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "f7dd7f86bc3907e4bf3dc671107c7bb131a067ec",
					}, types.DepHash{
						Algo: "sha256", Value: "19147453766c52d54b82bcc8c1e4bedeff5fcbd72e8ac501379c3194ae658bfb",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-386/1.10.0/.zip",
		},
	}, "windows-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1922328, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "d1cf419b87ec31b372f746b3495dc6dd5b0bfc70",
					}, types.DepHash{
						Algo: "sha256", Value: "285725fd4998b59d4591121c2b9e0ff4d15bc584e20712b215317142b9c6f937",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 593696, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "907ad47e79fec3829d14223c04ec41032caaf811",
					}, types.DepHash{
						Algo: "sha256", Value: "73b7235bfa41907b8770e1fe0f8b4cb35d5b5a89a7cb72f0c5658a53fd5575ad",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-amd64/1.10.0/.zip",
		},
	}, "windows-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1783584, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "9c6b24e8291087317af3e9213f0be6c02e305d74",
					}, types.DepHash{
						Algo: "sha256", Value: "16e45b474e689f7c315f22f4322832ac96783205afba5efb6133c13e64e4bce6",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 529688, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "c1b0321b8efab458b7a7a8bbf628c681ef9d1eea",
					}, types.DepHash{
						Algo: "sha256", Value: "7b313ba72bef5b11cf9f5797a69712648ce16acfc2f46d0acf28f90832fa92d1",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-arm64/1.10.0/.zip",
		},
	},
}
