// Code generated by go generate; DO NOT EDIT.
// Generated at 2026-01-27 18:06:21.259850253 -0800 PST m=+0.760738549
// For version 1.7.0, base URL https://broth.itch.zone/libc7zip
package formulas

import "github.com/itchio/boar/szextractor/types"

var ByOsArch = types.DepSpecMap{
	"darwin-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2276972, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "95ab0692ecdccd46779d4fc0be86393b86f7c935",
					}, types.DepHash{
						Algo: "sha256", Value: "52cabfff2930ff581b94ac79c16df2844755f9c60bd0f1dab3499ce2a9e58de3",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.dylib", Size: 160152, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "02cd54c68ac13ff43d47a47464efc9e8ec29e8cf",
					}, types.DepHash{
						Algo: "sha256", Value: "ad7ed32daa87c565de098c9b425d777ec430c77590ffc9e50231c2ab7d1e2481",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-amd64/1.7.0/.zip",
		},
	}, "darwin-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "darwin-arm64/", Size: 0, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "da39a3ee5e6b4b0d3255bfef95601890afd80709",
					}, types.DepHash{
						Algo: "sha256", Value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
					},
				},
			}, types.DepEntry{
				Name: "darwin-arm64/7z.so", Size: 2092056, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "74c407f13f20818715e717c429ea4b35a61ca601",
					}, types.DepHash{
						Algo: "sha256", Value: "cd03e851931f1e5e356e44ad3e611e9cdb7c7985199a214bc915fffe8e405dcf",
					},
				},
			}, types.DepEntry{
				Name: "darwin-arm64/libc7zip.dylib", Size: 179600, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "279a07299c006f82578d863c19b8992bae7fbe41",
					}, types.DepHash{
						Algo: "sha256", Value: "7715bc55baf65ea14c818f0fb816f5dc997292af6a4fd0a7b4a3be8095259909",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/darwin-arm64/1.7.0/.zip",
		},
	}, "linux-386": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2291392, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "5a3313d9d69ce3fe648022a7aa588b0c5195de65",
					}, types.DepHash{
						Algo: "sha256", Value: "1cc4e611b4cc91de144fe12e9fbc5242f775d37574c6eda261e3d6fd888c9c2b",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 174240, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "90c1a4c0604ca82a167b8e97dc42df3a55f7e90e",
					}, types.DepHash{
						Algo: "sha256", Value: "d590413f925d7dc88b18425546b113a67767ff516612c04829043e163e84b6bf",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-386/1.7.0/.zip",
		},
	}, "linux-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.so", Size: 2273248, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "ff47097a16402a6144e868daff4416e6ab8c2584",
					}, types.DepHash{
						Algo: "sha256", Value: "23f949fdbcb3cb0722539d728824138c8b5048577d9de350ceb17da0071b3a99",
					},
				},
			}, types.DepEntry{
				Name: "libc7zip.so", Size: 193584, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "6b1dc63e86ec1611bee6c3977ab23b271d51a23c",
					}, types.DepHash{
						Algo: "sha256", Value: "fc84baec5736acaf3e9a29f59168a0f958c81cfe8a3fb8a5a5ba0d480b23dec6",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-amd64/1.7.0/.zip",
		},
	}, "linux-arm64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "linux-arm64/", Size: 0, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "da39a3ee5e6b4b0d3255bfef95601890afd80709",
					}, types.DepHash{
						Algo: "sha256", Value: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
					},
				},
			}, types.DepEntry{
				Name: "linux-arm64/7z.so", Size: 2323792, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "a8c15e3621e326a0298dbcb516d7bb469ccbc2b2",
					}, types.DepHash{
						Algo: "sha256", Value: "a323bce742109c23c89a4353e44f47ce36bb7b71c4ac8574e00ddedacd587868",
					},
				},
			}, types.DepEntry{
				Name: "linux-arm64/libc7zip.so", Size: 208744, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "319ce9950e0b80015023cd9160ad08835b7a8b31",
					}, types.DepHash{
						Algo: "sha256", Value: "3c745898e13fa7084a1c0e51ec11864ba612ba5f4dc883a874c76c814d2c63d9",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/linux-arm64/1.7.0/.zip",
		},
	}, "windows-386": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1080424, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "f67bbeb9ddd3d4a7b8d77e36b96f9bd119af056d",
					}, types.DepHash{
						Algo: "sha256", Value: "086eabcc6015e36c9c11d4eaba33a3d16ddc3eddcb329cba1f10cc498025de42",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 398952, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "23784a4df4fe9e1234e47ddd6c2ec281ae70e6b4",
					}, types.DepHash{
						Algo: "sha256", Value: "349a0dc547080179812817c74c4321f4b51f6cb1b475e8c283f7ee7d4774ba08",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-386/1.7.0/.zip",
		},
	}, "windows-amd64": types.DepSpec{
		Entries: []types.DepEntry{
			types.DepEntry{
				Name: "7z.dll", Size: 1615976, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "ce4d5b8565fa6665ef438b645fdf497914077f70",
					}, types.DepHash{
						Algo: "sha256", Value: "dad12b9fa46415f1226624c06d4442f7f6a20f3ba7e075a8ebe1f0c926e4f19b",
					},
				},
			}, types.DepEntry{
				Name: "c7zip.dll", Size: 541288, Hashes: []types.DepHash{
					types.DepHash{
						Algo: "sha1", Value: "5b1e48af9515cdbb2a1776e19ce2f82854820479",
					}, types.DepHash{
						Algo: "sha256", Value: "899e20f3b9f81478aa8b2f00ee260d7443747ba75961523931b8d3c05ba4b7f2",
					},
				},
			},
		}, Sources: []string{
			"https://broth.itch.zone/libc7zip/windows-amd64/1.7.0/.zip",
		},
	},
}
